MountainTrainingApp.Web/Controllers/AerobicWorkoutController.cs
namespace MountainTrainingApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Globalization;
    using Web.ViewModels.AerobicWorkout;
    using Services.Data.Interfaces;
    using static Common.GeneralApplicationConstats;
    using static Common.NotificationMessagesConstants;
    using Web.Infrastructure.Extensions;
    using MountainTrainingApp.Services.Data.Models.AerobicWorkout;

    [Authorize]
    public class AerobicWorkoutController : Controller
    {
        private readonly IAerobicActivityService aerobicActivityService;
        private readonly IAerobicWorkoutService aerobicWorkoutService;
        private readonly ITrainingPeriodService trainingPeriodService;
        private readonly IDayOfWeekService dayOfWeekService;
        private readonly ITrainerService trainerService;
        public AerobicWorkoutController(IAerobicActivityService aerobicActivityService
            ,IAerobicWorkoutService aerobicWorkoutService
            ,ITrainingPeriodService trainingPeriodService
            ,IDayOfWeekService dayOfWeekService
            ,ITrainerService trainerService)
        {
            this.aerobicActivityService = aerobicActivityService;
            this.aerobicWorkoutService = aerobicWorkoutService;
            this.trainingPeriodService = trainingPeriodService;
            this.dayOfWeekService = dayOfWeekService;
            this.trainerService = trainerService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]IndexQueryModel queryModel)
        {
            IndexWorkoutsFilteredAndPagedServiceModel model =await aerobicWorkoutService.AllAerobicWorkoutsAsync(queryModel);

            queryModel.AerobicWorkouts= model.AerobicWorkouts;

            queryModel.TotalWorkouts = model.TotalWorkoutsCount;

            queryModel.Types = await 
                aerobicActivityService.AllAerobicActivitiesNamesAsync();

            return View(queryModel);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model=new AerobicWorkoutAddViewModel();
            model.AerobicActivities =
                await aerobicActivityService.AllAerobicActivitiesAsync();

            model.TrainingPeriods=
                await trainingPeriodService.GetTrainingPeriodsAsync();

            model.DaysOfWeek=
                await dayOfWeekService.DaysOfWeekAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AerobicWorkoutAddViewModel model)
        {
           
            bool aerobicActivitiesExist = await
                aerobicActivityService.AerobicActivityExistByIdAsync(model.AerobicActivityId);

            if (!aerobicActivitiesExist)
            {
                ModelState.AddModelError(nameof(model.AerobicActivityId), "Invalid activity id!");
            }

            bool trainningPeriodExist=await 
                trainingPeriodService.TrainingPeriodExistByIdAsync(model.TrainingPeriodId);

            if (!trainningPeriodExist)
            {
                ModelState.AddModelError(nameof(model.TrainingPeriodId), "Invalid period id!");
            }

            bool dayOdWeekExist=await
                dayOfWeekService.DayOfWeekExistByIdAsync(model.DayOfWeekId);

            if (!dayOdWeekExist)
            {
                ModelState.AddModelError(nameof(model.DayOfWeekId), "Invalid day id!");
            }


            if (!ModelState.IsValid)
            {
                model.AerobicActivities =
                   await aerobicActivityService.AllAerobicActivitiesAsync();

                model.TrainingPeriods =
                    await trainingPeriodService.GetTrainingPeriodsAsync();

                model.DaysOfWeek =
                    await dayOfWeekService.DaysOfWeekAsync();

                return View(model);
            }

            bool isDateValid = DateTime.TryParseExact(model.DateAndTime, DateFormat, CultureInfo.InvariantCulture
               , DateTimeStyles.None, out DateTime dateAndTime);

            if (!isDateValid)
            {

                model.AerobicActivities =
                    await aerobicActivityService.AllAerobicActivitiesAsync();

                model.TrainingPeriods =
                    await trainingPeriodService.GetTrainingPeriodsAsync();

                model.DaysOfWeek =
                    await dayOfWeekService.DaysOfWeekAsync();

                return View(model);
            }

            try
            {
                string athlettId = User.GetUserId();
                await aerobicWorkoutService.CreateAerobicWorkoutAsync(model,athlettId,dateAndTime);

            }
            catch (Exception _)
            {

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {

            bool workoutExist = await aerobicWorkoutService
                .AerobicWorkoutExistByIdAsync(id);

            if (!workoutExist)
            {
                TempData[ErrorMesage] = "Aerobic workout with the provided id does not exist";

                return RedirectToAction(nameof(Index));
            }

            var model = await
                aerobicWorkoutService.GetDetailsByIdAsync(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AerobicWorkoutEditViewModel model,string id)
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Mine(string id)
        {
            List<AerobicWorkoutIndexViewModel> myAerobicWorkouts = 
                new List<AerobicWorkoutIndexViewModel>();

            string athletId=User.GetUserId();
            bool isUserTrainer=await 
                trainerService.TainerExistByUserIdAsync(athletId);

            if (isUserTrainer)
            {
                string trainerId = await
                    trainerService.GetTrainerIdByUserId(athletId);

                myAerobicWorkouts.AddRange(await aerobicWorkoutService.AllByTrainerIdAsync(trainerId));
            }
            else 
            {
                myAerobicWorkouts.AddRange(await aerobicWorkoutService.AllByAthletIdIdAsync(athletId));
            }

            return View(myAerobicWorkouts);
        }
    }
}

MountainTrainingApp.Web/Controllers/ClimbingController.cs
namespace MountainTrainingApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MountainTrainingApp.Services.Data.Interfaces;
    using MountainTrainingApp.Web.Infrastructure.Extensions;
    using MountainTrainingApp.Web.ViewModels.Climbing;
    using System.Globalization;

    [Authorize]
    public class ClimbingController : Controller
    {
        private readonly IClimbingActivityService climbingActivityService;
        private readonly IClimbingService climbingService;
        private readonly ITrainingPeriodService trainingPeriodService;
        private readonly IDayOfWeekService dayOfWeekService;
       
        public ClimbingController(IClimbingActivityService climbingActivityService
            , IClimbingService climbingService
            , ITrainingPeriodService trainingPeriodService
            , IDayOfWeekService dayOfWeekService)
        {
            this.climbingActivityService = climbingActivityService;
            this.climbingService = climbingService;
            this.trainingPeriodService = trainingPeriodService;
            this.dayOfWeekService = dayOfWeekService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await
                climbingService.AllClimbingsAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new ClimbingAddViewModel();

            model.TrainingPeriods= await
                trainingPeriodService.GetTrainingPeriodsAsync();

            model.ClimbingActivities=await
                climbingActivityService.AllClimbingActivitiesAsync();

            model.DaysOfWeek=await
                dayOfWeekService.DaysOfWeekAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ClimbingAddViewModel model)
        {
            bool climbingActivityExist=await 
                climbingActivityService.ClimbingActivityExistByIdAsync(model.ClimbingActivityId);

            if (!climbingActivityExist)
            {
                ModelState.AddModelError(nameof(model.ClimbingActivityId), "Invalid activity id!");
            }

            bool trainningPeriodExist = await
              trainingPeriodService.TrainingPeriodExistByIdAsync(model.TrainingPeriodId);

            if (!trainningPeriodExist)
            {
                ModelState.AddModelError(nameof(model.TrainingPeriodId), "Invalid period id!");
            }

            bool dayOdWeekExist = await
                dayOfWeekService.DayOfWeekExistByIdAsync(model.DayOfWeekId);

            if (!dayOdWeekExist)
            {
                ModelState.AddModelError(nameof(model.DayOfWeekId), "Invalid day id!");
            }

            if (!ModelState.IsValid)
            {

                model.TrainingPeriods = await
                    trainingPeriodService.GetTrainingPeriodsAsync();

                model.ClimbingActivities = await
                    climbingActivityService.AllClimbingActivitiesAsync();

                model.DaysOfWeek = await
                    dayOfWeekService.DaysOfWeekAsync();

                return View(model);
            }

            bool isDateValid = DateTime.TryParseExact(model.DateAndTime, Common.GeneralApplicationConstats.DateFormat, CultureInfo.InvariantCulture
             , DateTimeStyles.None, out DateTime dateAndTime);


            if (!isDateValid)
            {
                model.ClimbingActivities = await
                   climbingActivityService.AllClimbingActivitiesAsync();

                model.TrainingPeriods =
                    await trainingPeriodService.GetTrainingPeriodsAsync();

                model.DaysOfWeek =
                    await dayOfWeekService.DaysOfWeekAsync();

                return View(model);
            }

            try
            {
                string athlettId = User.GetUserId();
                await climbingService.CreateClimbingAsync(model, athlettId, dateAndTime);

            }
            catch (Exception _)
            {

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

MountainTrainingApp.Web/Controllers/StrengthController.cs
namespace MountainTrainingApp.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Globalization;
    using MountainTrainingApp.Services.Data.Interfaces;
    using Web.Infrastructure.Extensions;
    using Web.ViewModels.Strength;
    using Microsoft.AspNetCore.Authorization;

    [Authorize]
    public class StrengthController : Controller
    {
        private readonly IStrengthService strengthService;
        private readonly IStrengthWorkoutTypeService strengthWorkoutTypeService;
        private readonly IDayOfWeekService dayOfWeekService;
        private readonly ITrainingPeriodService trainingPeriodService;

        public StrengthController(IStrengthService strengthService 
            ,IStrengthWorkoutTypeService strengthWorkoutTypeService
            ,IDayOfWeekService dayOfWeekService
            ,ITrainingPeriodService trainingPeriodService)
        {
            this.strengthService = strengthService;
            this.strengthWorkoutTypeService= strengthWorkoutTypeService;
            this.dayOfWeekService = dayOfWeekService;
            this.trainingPeriodService = trainingPeriodService;
        }
        public async Task<IActionResult> Index()
        {
            var model= await strengthService.AllStrengthWorkoutsAsync();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new StrengthAddViewModel();
            model.TrainingPeriods = 
                await trainingPeriodService.GetTrainingPeriodsAsync();
            model.DaysOfWeek=
                await dayOfWeekService.DaysOfWeekAsync();
            model.StrengthWorkoutTypes=
                await strengthWorkoutTypeService.AllStrengthWorkoutsAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(StrengthAddViewModel model)
        {
            bool strengthTypeExist = await
              strengthWorkoutTypeService.StrengthWorkoutExistByIdAsync(model.StrengthWorkoutTypeId);

            if (!strengthTypeExist)
            {
                ModelState.AddModelError(nameof(model.StrengthWorkoutTypeId), "Invalid type id!");
            }

            bool trainningPeriodExist = await
                trainingPeriodService.TrainingPeriodExistByIdAsync(model.TrainingPeriodId);

            if (!trainningPeriodExist)
            {
                ModelState.AddModelError(nameof(model.TrainingPeriodId), "Invalid period id!");
            }

            bool dayOdWeekExist = await
                dayOfWeekService.DayOfWeekExistByIdAsync(model.DayOfWeekId);

            if (!trainningPeriodExist)
            {
                ModelState.AddModelError(nameof(model.DayOfWeekId), "Invalid day id!");
            }


            if (!ModelState.IsValid)
            {
                model.StrengthWorkoutTypes =
                   await strengthWorkoutTypeService.AllStrengthWorkoutsAsync();

                model.TrainingPeriods =
                    await trainingPeriodService.GetTrainingPeriodsAsync();

                model.DaysOfWeek =
                    await dayOfWeekService.DaysOfWeekAsync();

                return View(model);
            }

            bool isDateValid = DateTime.TryParseExact(model.DateAndTime, Common.GeneralApplicationConstats.DateFormat
                , CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime dateAndTime);

            if (!isDateValid)
            {

                model.StrengthWorkoutTypes =
                    await strengthWorkoutTypeService.AllStrengthWorkoutsAsync();

                model.TrainingPeriods =
                    await trainingPeriodService.GetTrainingPeriodsAsync();

                model.DaysOfWeek =
                    await dayOfWeekService.DaysOfWeekAsync();
                return View(model);
            }

            try
            {
                string athlettId = User.GetUserId();
                await strengthService.CreateStrengthWorkoutAsync(model, athlettId, dateAndTime);

            }
            catch (Exception _)
            {

                throw;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

MountainTrainingApp.Web/Views/Shared/_Layout.cshtml
@using static MountainTrainingApp.Common.GeneralApplicationConstats;
@{  
    int currentYear = DateTime.UtcNow.Year;
    string footerNote = (currentYear == ReleasedYear) ? $"{currentYear}"
    : $"{ReleasedYear} - {currentYear}";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MountainTrainingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MountainTrainingApp.Web.styles.css" asp-append-version="true" />
    <link rel="manifest" href="/site.webmanifest">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <partial name="_NotificationPartial" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mountain Training App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                          
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Aerobic</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="AerobicWorkout" asp-action="Index">Aerobic</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="AerobicWorkout" asp-action="Add">Add Aerobic</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="AerobicWorkout" asp-action="Mine">Mine Aerobic</a>
                                </div>
                            </li>                       

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Strength</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Strength" asp-action="Index">Strength</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Strength" asp-action="Add">Add Strength</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Climbing</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Climbing" asp-action="Index">Climbing</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Climbing" asp-action="Add">Add Climbing</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }   
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;@footerNote Mountain Training App
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MountainTrainingApp.Web/Views/Shared/_NotificationPartial.cshtml
@using static MountainTrainingApp.Common.NotificationMessagesConstants;
@if (TempData.ContainsKey(ErrorMesage))
{
    <script>toastr.error('@TempData[ErrorMesage]')</script>

}

@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]')</script>
}

@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]')</script>
}

@if (TempData.ContainsKey(SuccesMessage))
{
    <script>toastr.success('@TempData[SuccesMessage]')</script>
}